# Generated by Django 3.0.2 on 2021-01-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alemsite', '0002_auto_20210119_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
