# Generated by Django 3.0.2 on 2021-01-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alemsite', '0005_auto_20210121_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Size'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Status'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Subcategory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Update'),
        ),
    ]
