# Generated by Django 3.0.2 on 2021-01-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alemsite', '0006_auto_20210121_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Gender'),
        ),
    ]
